#!/bin/sh
set -e

export LLVM_UTIL_ROOT=$(dirname ${BASH_SOURCE[0]})

CWD=$(pwd)
while [[ $CWD != "/" && $(basename $CWD) != "llvm-project" ]]; do
  CWD=$(dirname $CWD)
done

if [[ $(basename $CWD) == "llvm-project" ]]; then
  echo "Found LLVM Root: $CWD"
  export LLVM_PROJECT_ROOT=$CWD
else
  echo "Did not find llvm-project root!"
  exit 1
fi

if [ -z "$1" ]; then
  echo "Missing subcommand. Possible subcommands are"
  ls $LLVM_UTIL_ROOT/subcommands
  exit 2
fi

SUBCOMMAND="$1"
SUBCOMMAND_PATH=$LLVM_UTIL_ROOT/subcommands/$SUBCOMMAND

if ! [ -f $SUBCOMMAND_PATH ]; then
  echo "Subcommand '$SUBCOMMAND' not found"
  exit 2
fi

$SUBCOMMAND_PATH ${@:2}
