#!/bin/sh

set -e
cd $LLVM_PROJECT_ROOT/
if [ -d build ]; then
  read -p "This command triggers a rebuild. Are you sure? [y/N] " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
  fi
fi  
rm -rf build
mkdir build
cd build

BUILD_CONFIG=$LLVM_PROJECT_ROOT/build-config

# If a build config is not set up, add this file to the repo. 
# This is by default ignored by .gitignore
if [ ! -f $BUILD_CONFIG ]; then
  cp -f $LLVM_UTIL_ROOT/default-build-config $BUILD_CONFIG
fi

CMAKE_FLAGS=$(awk '{print "-D" $0}' $BUILD_CONFIG)

eval cmake -G Ninja $CMAKE_FLAGS ../llvm

$LLVM_UTIL_ROOT/subcommands/build $@
